# Valid TOML config file
data-path="/usr/app/data" # Path

# Network
bootnodes=["enode://4c6e6a5b597c0089282d7f9172b48caa62234dd345c60607e74a2af088a8d548343c9418914d1da56f7fb89c85592147b800bcf1b88db5abc637e6a9c76fe684@127.0.0.1:30303"]

rpc-http-enabled=true
rpc-http-api=["ETH","NET","IBFT"]
rpc-http-port=8546

p2p-port=30304

host-allowlist=["*"]

rpc-http-cors-origins=["all"]

# Chain
genesis-file="/usr/app/genesis.json" # Path to the custom genesis file
min-gas-price=0
